ENVIRONMENT:
  MAX_EPISODE_STEPS: 50000
SIMULATOR:
  TURN_ANGLE: 3
  TILT_ANGLE: 30
  FORWARD_STEP_SIZE: 0.05
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    HFOV: 90
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    HFOV: 90
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    HFOV: 90
    MIN_DEPTH: 0.5
    MAX_DEPTH: 8.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: Nav-v0

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'GPS_SENSOR', 'COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  DATA_PATH: /home/kirill/habitat-lab/data/datasets/pointnav/pointnav_mipt/train_mipt.json.gz
