MODEL:
  TYPE: "oneformer"
  CONFIG: ./weights/config_oneformer_ade20k.yaml
  WEIGHTS: ../../outputs/hm3d2_ade20k_640k_bs4/model_0159999.pth
  NUM_CLASSES: 150
  NUM_ACTIONS: 2
DATASET:
  TRAIN:
    TYPE: "multistep"
    MODE: "train"
    ANNOTATION_ROOT: "/data/interactron_ade_4_steps/annotations/interactron_v1_train-Copy2.json"
    IMAGE_ROOT: "/data/interactron_ade_4_steps/train"
  TEST:
    TYPE: "multistep"
    MODE: "test"
    ANNOTATION_ROOT: "/data/interactron_ade_4_steps/annotations/interactron_v1_val-Copy1.json"
    IMAGE_ROOT: "/data/interactron_ade_4_steps/val"
TRAINER:
  TYPE: "single_frame"
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  START_EPOCH: 1
  MAX_EPOCHS: 50
  SAVE_WINDOW: 10
  DETECTOR_LR: 1e-5
  SUPERVISOR_LR: 1e-4
  BETA1: 0.9
  BETA2: 0.95
  MOMENTUM: 0.9
  GRAD_NORM_CLIP: 1.0
  WEIGHT_DECAY: 0.1
  OPTIM_TYPE: "Adam"
  LR_DECAY: False
  WARMUP_TOKENS: 0
  FINAL_TOKENS: 1.0e7
  OUTPUT_DIRECTORY: "training_results/single_frame_baseline_ade_150"
EVALUATOR:
  TYPE: "random_policy_evaluator"
  BATCH_SIZE: 1
  NUM_WORKERS: 1
  OUTPUT_DIRECTORY: "evaluation_results/single_frame_baseline"
  CHECKPOINT: "training_results/single_frame_baseline/05-23-2023:17:29:45/detector_5.pt"

